
## Executive Summary {-}

The purpose of the Nuxalk Watershed Connectivity Restoration Plan (WCRP) is to improve understanding of habitat connectivity for Chinook Salmon (*Oncorhynchus tschawystcha*), Coho Salmon (*O. kisutch*), and Sockeye Salmon (*O. nerka*), herein referred to as Pacific salmon, in the Atnarko River, Necleetsconnay River, and Bella Coola River watersheds and inform Nuxalk Nation’s efforts to close knowledge gaps and plan and prioritize restoration. Local data and knowledge are combined with connectivity modelling to estimate current connectivity status and identify structures that potentially block the most habitat. This informs the prioritization of field assessments to close the most significant knowledge gaps efficiently. Information from field assessments of barrier status and habitat condition are incorporated into the model, improving understanding of which barriers block the most habitat, and informing restoration prioritization. As knowledge gaps are closed and barriers are addressed, this plan will be revised to summarize progress and provide updated estimates of connectivity status and the status and relative importance of remaining structures.

In the Atnarko River, Necleetsconnay River, and Bella Coola River watersheds, X km of Pacific salmon habitat are currently connected to the ocean and X km are disconnected from it. This means that X% of the X km of total habitat is connected.

In the Atnarko River, Necleetsconnay River, and Bella Coola River watersheds, X structures potentially disconnect Pacific salmon habitat. Of these, X are identified as barriers in need of rehabilitation (priority barriers), X are identified as barriers that do not warrant rehabilitation (non-actionable), and X require further field assessment.

![Figure 1: Map of Pacific salmon habitat and structures that are confirmed or potential barriers to fish passage in the Atnarko River, Necleetsconnay River, and Bella Coola River watersheds as of May 2026. Structure data were obtained from BCFishPass and the Canadian Aquatic Barriers Database (aquaticbarriers.ca). The accessibility model represents areas of the watershed that one or more Pacific salmon species could access naturally in the absence of anthropogenic barriers. The habitat model represents the subset of accessible waterbodies that may be used by one or more Pacific salmon species for spawning or rearing. Available local knowledge and data were incorporated and overruled habitat model results. Thick red lines represent habitat considered to be fully disconnected (upstream of barriers or unassessed structures). ](content/images/Figure_1_Map.png)
 
![Figure 2: Habitat Accumulation Curve (HAC) showing structures in the Atnarko River, Necleetsconnay River, and Bella Coola River watersheds as of May 2026. Structures are ranked based on how much (km) habitat for Pacific salmon is upstream. The primary y-axis represents the cumulative amount of potential habitat gain (km). Sets of structures are indicated by a grey line below the curve, indicating that gains from addressing the downstream structure alone would be less than the combined gains from addressing all structures in the set. Habitat upstream of unassessed structures is considered disconnected until field assessments are completed. Structures that were excluded as passable are not shown.](content/images/Fig_2_HAC.png)

This WCRP was initiated in 2023. Since then, the passability of X structures has been assessed and the model updated to reflect the status of these assessed structures.