# Appendix A – Status of Structures Assessed in the Field {-}

## Non-Actionable Barriers
No non-actionable barriers were identified through the implementation of this WCRP as of May 2026. 

## Data-deficient Barriers {-}
```{r echo = FALSE}
#| label: table-2
#| tbl-cap: "Table 2: Structures in Atnarko River, Necleetsconnay River, and Bella Coola River watersheds that have been assessed for fish passage for Pacific salmon as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat values."
#| warning: false
source("Rscripts/table_formatting.R")
data <- read.csv("tracking-tables/tbl-2-data-deficient.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```
## Excluded Structures {-}
```{r echo = FALSE}
#| label: table-3
#| tbl-cap: "Table 3: Structures in Atnarko River, Necleetsconnay River, and Bella Coola River watersheds that are excluded from further consideration in subsequent ranking and work planning because the structure is not present, is confirmed passable (e.g., bridge), or has no habitat upstream for Pacific salmon."
#| warning: false
source("Rscripts/table_formatting.R")
data <- read.csv("tracking-tables/tbl-3-excluded-structures.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```



