
# Acknowledgements and References {-}

## Recommended Citation 
W. Millar, S. Dodds, J. Moody, T. Mack, I. Pootlass, I. Siwallace, N. Mazany-Wright, F. Montgomery, B. Rebellato, S. Sra, L. Bernardi, O. Koppel, and N. W. R. Lapointe. 2026. Nuxalk watershed connectivity restoration plan. Nuxalk Nation, Bella Coola, B.C. and Canadian Wildlife Federation. Ottawa, Ontario, Canada. 

## Acknowledgements {-}
Canadian Wildlife Federation recognizes that the lands and waters that form the basis of this plan are the traditional unceded territory of the Nuxalk and Ulkatcho First Nations. Plan development and implementation was funded by the B.C. Salmon Restoration and Innovation Fund. Members of the planning team ([Appendix B](appendix-b.qmd)) are passionate about the conservation and restoration of freshwater ecosystems and the species they support, and contributed feedback, guidance, and knowledge. Model outputs were further refined based on feedback provided by local knowledge holders beyond the planning team. Accessibility models were inspired by fish-passage prioritization approaches developed by British Columbia’s Fish Passage Technical Working Group.


## References {-}
Bella Coola Watershed Conservation Society. 2007. Bella Coola watershed-based fish sustainability plan stage II. Prepared for communities of Bella Coola Valley and Fisheries and Oceans Canada.  

DeMarco, R. 1989. Fish Habitat Inventory & Information Program stream summary catalogue: subdistrict #8 Bella Coola. Prepared by SHIP Environmental Consultants Ltd. for Fisheries and Oceans Canada North Coast Division. Available: https://waves-vagues.dfo-mpo.gc.ca/library-bibliotheque/40601456.pdf [accessed May 2026]. 

Osmond-Jones and Bonner. 1975. A reconnaissance survey of Stillwater Lake. B.C. Ministry of Environment lakes files. Available: https://a100.gov.bc.ca/pub/acat/documents/r12321/LakeSurveyData-StillwaterLake1975_1204764410638_8e248a68ce6e6780206a2a442c58bb2b06fbd29f7c5.pdf [accssed May 2026]. 

Shortreed, K., K. F. Morton, K. Malange, and J. M. B. Hume. Factors Limiting Juvenile Sockeye Production and Enhancement Potential For Selected B.C. Nursery Lakes. Canadian Science Advisory Secritariat Research Document 2001/098. 

Summit Environmental Consultants. 1996. Final report level 1 coastal watershed assessment (CWAP) Bella Coola River watershed. Prepared for Ministry of Environment, Lands and Parks, Williams Lake, B.C. Available: https://a100.gov.bc.ca/pub/acat/documents/r8259/bellacoola_cwapL1_1996_1164821652308_250afa4b769a45bc80adcc44b20b8ffe.pdf [accessed May 2026]. 

Summit Environmental Consultants Ltd. 1997. Sediment source inventory, stream channel assessment, and fish habitat assessment: Lower Bella Coola River watershed. Prepared for Ministry of Environment, Lands and Parks, Williams Lake, B.C. Available: https://a100.gov.bc.ca/pub/acat/documents/r8011/HQ2293_1159821815847_31bb0f95dbba4f098044b15d187c3caa.pdf [accessed May 2026]. 

Triton Environmental Consultants. 2011. Bella Coola Highway 20 salvage. B.C. fish collection permit NAWL-66722 XHAB 177 2010. Available: https://a100.gov.bc.ca/pub/acat/public/viewReport.do?reportId=23021 [accessed May 2026]. 
